name: Make Low Poly GLB

on:
  workflow_dispatch:
    inputs:
      filename:
        description: 'Input file to convert to low poly GLB'
        required: true
      target_faces:
        description: 'Target number of the low poly model'
        required: false
        default: 6000
      texture_resolution:
        description: 'Texture size'
        required: false
        default: 1024
      multiresolution_levels:
        description: 'Multiresolution levels'
        required: false
        default: 4

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: checkout repo
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.10.11

      - name: Install Blender and Typer
        run: |
          python -m pip install --upgrade pip
          python -m pip install --upgrade bpy --extra-index-url https://github.com/michaelgold/buildbpy
          python -m pip install --upgrade requests python-dotenv typer=='0.9.0' httpx

      - name: Convert to Low Poly
        run: |
          python lowpoly.py ${{ github.event.inputs.filename }} --target-faces ${{ github.event.inputs.target_faces }} --texture-resolution ${{ github.event.inputs.texture_resolution }} --multiresolution-levels ${{ github.event.inputs.multiresolution_levels }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Upload GLB file as an artifact
        uses: actions/upload-artifact@v4
        with:
          name: lowpoly-mesh
          path: |
            ./*.glb